#!/bin/bash

source jeu.sh
source jeu1.sh
source jeu2.sh
source jeu3.sh
source regle_jeu.sh
source jeu4.sh

jeu2()
{
    quit="quit"
    echo -e "\n\t1-rock\n\t2-paper\n\t3-scissors\n" 
    read -p "Your choice: " nb
    rand=$(($RANDOM% 3 + 1))
    if [ "$nb" = "$rand" ]
        then
        echo "Equality"
    elif [ "$nb" = 1 ] 
        then    Rock2 rand
    elif [ "$nb" = 2 ]  
        then    Paper2 rand   
    elif [ "$nb" = 3 ]   
        then    Scissors2 rand 
    elif [ "$nb" = "return" ] 
        then
                main
    elif [ "$nb" = "quit" ]
        then    clear
        echo "see you on shifumi"
        my_score=a
        my_score=$(($my_score + 1))
        return 0
    else
            echo -e "\t\t\tRecommencer l'entree n'est pas valable"
    fi
}

jeu1()
{
    quit="quit"
    echo -e "\n\t1-rock\n\t2-paper\n\t3-scissors\n" 
    read -p "Your choice: " nb
    rand=$(($RANDOM% 3 + 1))
    if [ "$nb" = "$rand" ]
    then
    echo "Equality"
    elif [ "$nb" = 1 ] 
        then    Rock1 rand
    elif [ "$nb" = 2 ]  
        then    Paper1 rand
    elif [ "$nb" = 3 ]   
        then    Scissors1 rand
    elif [ "$nb" = "return" ] 
        then
        main
    elif [ "$nb" = "quit" ]
        then    clear
        echo "see you on shifumi"
        my_score=a
        my_score=$(($my_score + 1))
        return 0
    else
            echo -e "\t\t\tRecommencer l'entree n'est pas valable"
    fi
}


shifumi2()
{
    your_score=0
    my_score=0
    compteur=0
    echo -e "\n----------Ready to play Shifumi? Here we go!----------\n"
    while [[ "my_score" -lt "$a" ]] && [[ "your_score" -lt "$a" ]]; do
        jeu2
        done
    if [[ "my_score" -eq "$a" ]]
        then
        echo -e "\nVous avez gagne"
    elif [[ "my_score" -lt "$a" ]]
        then
        echo -e "\nVous avez perdu"
    fi
}

shifumi1()
{
    my_score=0
    echo -e "\n----------Ready to play Shifumi? Here we go!----------\n"
    while [[ "my_score" -lt "$a" ]]; do
        jeu1
    done
    if [[ "my_score" -eq "$a" ]]
        then
        echo -e "\nVous avez gagne"
    fi
}

main()
{
    echo -e "\nBonjour, Veuillez selectionez votre mode de jeu :\n"
    echo -e "-1 : Shifumi basique, pas de perdant\n-2 : You vs IA"
    echo -e "-3 : Joueur vs Joueur\n-4 : Pierre-papier-ciseaux-lézard-Spock !"
    echo -e "-5 : Help / Rappel des regles\n-quit : quitter le jeu"
    echo -e "-return : retourne au menu en jeu\n"
    read -p "Quel mode de jeux vous interesse ?  " choix
    if [ "$choix" = 1 ] 
        then    shifumi1 $a
    elif [ "$choix" = 2 ]  
        then    shifumi2 $a    
    elif [ "$choix" = 3 ]   
        then    shifumi3 $a
    elif [ "$choix" = 4 ]   
        then    shifumi4 $a
    elif [ "$choix" = 5 ]   
        then    regle_jeu $a
    elif [ "$choix" = "quit" ]   
        then    return
    else
         echo -e "\t\t\tRecommencer l'entree n'est pas valable"
         main $a
    fi
}


z=$1
if [ $# -eq 0 ]
    then
    echo "Veuillez entrer un argument (Il correspond au nb de manche)"
elif [ $# -gt 1 ]
    then
    echo "Veuillez ne mettre qu'un seul argument !"
elif ! [[ "$z" =~ ^[0-9]+$ ]]
    then
    echo "Veuillez entrez un nombre (superieur a 0)"
elif [[ "$z" -lt 1 ]]
    then
    echo "Veuillez entrez un nombre superieur a 0"
else
    a=$1
    main $a
fi