#!/bin/bash

Rock1()
{
    if [ "$rand" = 2 ] 
    then
    echo -e "\033[31m\t\n\t\tpaper covers rock\n"
    my_score=$(($my_score - 1))
    echo -e "\033[0mscore :" $my_score
    else
    echo -e "\033[32m\n\t\trock crushes scissors\n"
    my_score=$(($my_score + 1))
    echo -e "\033[0mscore :" $my_score
    fi
}

Paper1()
{
    if [ "$rand" = 1 ] 
    then
    echo -e "\033[32m\n\t\tpaper covers rock\n"
    my_score=$(($my_score + 1))
    echo -e "\033[0mscore :" $my_score 
    else
    echo -e "\033[31m\n\t\tscissors cut paper\n"
    my_score=$(($my_score - 1))
    echo -e "\033[0mscore :" $my_score
    
    fi
}

Scissors1()
{
    if [ "$rand" = 1 ] 
    then
    echo -e "\033[31m\n\t\trock crushes scissors\n"
    my_score=$(($my_score - 1))
    echo -e "\033[0mscore :" $my_score 
    else
    echo -e "\033[32m\n\t\tscissors cut paper\n"
    my_score=$(($my_score + 1))
    echo -e "\033[0mscore :" $my_score
    
    fi
}

jeu1()
{
    quit="quit"
    echo -e "\n\t1-rock\n\t2-paper\n\t3-scissors\n" 
    read -p "Your choice: " nb
    rand=$(($RANDOM% 3 + 1))
    if [ "$nb" = "$rand" ]
    then
    echo "Equality"
    elif [ "$nb" = 1 ] 
        then    Rock1 rand
    elif [ "$nb" = 2 ]  
        then    Paper1 rand
    elif [ "$nb" = 3 ]   
        then    Scissors1 rand
    elif [ "$nb" = "return" ] 
        then
        main
    elif [ "$nb" = "quit" ]
        then    clear
        echo "see you on shifumi"
        my_score=a
        my_score=$(($my_score + 1))
        return 0
    else
            echo -e "\t\t\tRecommencer l'entree n'est pas valable"
    fi
}

shifumi1()
{
    my_score=0
    echo -e "\n----------Ready to play Shifumi? Here we go!----------\n"
    while [[ "my_score" -lt "$a" ]]; do
        jeu1
    done
    if [[ "my_score" -eq "$a" ]]
        then
        echo -e "\nVous avez gagne"
    fi
}

z=$1
if [ $# -eq 0 ]
    then
    echo "Veuillez entrer un argument (Il correspond au nb de manche)"
elif [ $# -gt 1 ]
    then
    echo "Veuillez ne mettre qu'un seul argument !"
elif ! [[ "$z" =~ ^[0-9]+$ ]]
    then
    echo "Veuillez entrez un nombre (superieur a 0)"
elif [[ "$z" -lt 1 ]]
    then
    echo "Veuillez entrez un nombre superieur a 0"
else
    a=$1
    shifumi1 $a
fi